---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: harbor.sandbox.haas.politie:443/platform-team/cf_tools
    tag: latest
    insecure_registries:
    - harbor.sandbox.haas.politie:443

inputs:
- name: resource-git-smoketests

run:
  path: resource-git-smoketests/ci/configure-uaa.sh

params:
  uaaadminpassword:
  uaaadminuser:
  uaaclientid:
  uaatarget:
  insecure:
