---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ruurdk/cf_tools

inputs:
- name: resource-git-smoketests

run:
  path: resource-git-smoketests/ci/configure-uaa.sh

params:
  uaaadminpassword:
  uaaadminuser:
  uaaclientid:
  uaatarget:
