---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rwwilden/cf_tools

inputs:
- name: resource-git-smoketests

run:
  path: resource-git-smoketests/ci/configure-uaa.sh

