---
jobs:
- name: push-smoketest-app
  build_logs_to_retain: 100
  public: false
  serial: true
  plan:
  - get: time-trigger
    trigger: true
  - get: resource-git-smoketests
  - task: task-deploy
    file: resource-git-smoketests/ci/deploy.yml
    params:
      api: {{cf-api}}
      username: {{cf-user}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: {{cf-space}}
      manifest: {{manifest_filename}}
  on_failure:
    put: slack-alert
    params:
      username: Smoke Alert
      icon_emoji: ':dash:'
      channel: ((slack_channel))
      silent: true
      text: "Smoke Detected while pushing smoketests app! Better check it out now!"
- name: push-smoketest-sso-resource
  build_logs_to_retain: 100
  public: false
  serial: true
  plan:
  - get: time-trigger
    trigger: true
  - get: resource-git-smoketests-sso-resource
  - task: task-deploy
    file: resource-git-smoketests-sso-resource/ci/deploy.yml
    params:
      api: ((cf-api))
      username: ((cf-user))
      password: ((cf-password))
      organization: ((cf-org))
      space: ((cf-space))
      manifest: {{manifest_filename}}
  on_failure:
    put: slack-alert
    params:
      username: Smoke Alert
      icon_emoji: ':dash:'
      channel: ((slack_channel))
      silent: true
      text: "Smoke Detected while pushing smoketests app! Better check it out now!"
- name: configure-uaa
  build_logs_to_retain: 100
  public: false
  serial: true
  plan:
  - get: time-trigger
    trigger: true
  - get: resource-git-smoketests
  - task: task-deploy
    file: resource-git-smoketests/ci/configure-uaa.yml
    params:
      uaatarget: ((uaa-target))
      uaaadminuser: ((uaa-admin-user))
      uaaadminpassword: ((uaa-admin-password))
      uaaclientid: ((uaa-client-id))
  on_failure:
    put: slack-alert
    params:
      username: Smoke Alert
      icon_emoji: ':dash:'
      channel: ((slack_channel))
      silent: true
      text: "Smoke detected while configuring UAA! Better check it out now!"
- name: run-tests
  build_logs_to_retain: 100
  public: false
  serial: true
  plan:
  - get: resource-git-smoketests
  - get: pcf-app-autoscaler
  - get: time-trigger
    trigger: true
    passed: [ push-smoketest-app, configure-uaa, push-smoketest-sso-resource ]
  - task: testscript
    file: resource-git-smoketests/ci/tests.yml
    params:
      CHECK_URL: ((check_url))
    on_failure:
      put: slack-alert
      params:
        username: Smoke Alert
        icon_emoji: ':dash:'
        channel: ((slack_channel))
        silent: true
        text: "Smoke Detected while running tests against smoketests app!"
  - task: scaletest
    file: resource-git-smoketests/ci/scale.yml
    params:
      api: ((cf-api))
      username: ((cf-user))
      password: ((cf-password))
      organization: ((cf-org))
      space: ((cf-space))
    on_failure:
      put: slack-alert
      params:
        username: Smoke Alert
        icon_emoji: ':dash:'
        channel: ((slack_channel))
        silent: true
        text: "Smoketest app refuses to scale down, better check the autoscaler!"

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: resource-git-smoketests
  type: git
  source:
    uri: ((git-uri-smoketests))
    private_key: ((git-private-key))

- name: resource-git-smoketests-sso-resource
  type: git
  source:
    uri: ((git-uri-smoketests-sso-resource))
    private_key: ((git-private-key))

- name: time-trigger
  type: time
  source:
    interval: ((interval))

- name: slack-alert
  type: slack-notification
  source:
    url: ((slack-webtoken))

- name: pcf-app-autoscaler
  type: pivnet
  source:
    api_token: {{api-token}}
    product_slug: pcf-app-autoscaler

